version: '3.8'

services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '3000:80'
    depends_on:
      - app
      - app.flask

  app:
    build:
      context: ./front-container
      args:
        - VITE_API_URL=${MOTORES_API_URL}
        - VITE_MODEL_HOST=${MODEL_HOST}
    volumes:
      - ./front-container/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VITE_API_URL=${MOTORES_API_URL}
      - VITE_MODEL_HOST=${MODEL_HOST}

  app.flask:
    build: 
      context: ./front-flask-container
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_TOPIC_MODEL=${KAFKA_TOPIC_MODEL}
      - MOTORES_API_URL=${MOTORES_API_URL}
    volumes:
      - ./front-flask-container/templates:/usr/local/app/templates
      - ./front-flask-container/static:/usr/local/app/static