version: '3.8'
services:
  fastapi-app:
    build: 
      context: .
    environment:
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_TOPIC_MODEL=${KAFKA_TOPIC_MODEL}
    ports:
      - "8000:8000"