version: '3.8'
services:
  fastapi-app:
    build: 
      context: .
    environment:
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_TOPIC_MODEL=${KAFKA_TOPIC_MODEL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    ports:
      - "4321:4321"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always